fix build-errors/warnings for mtk_eth_dbg
these are still there:

/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'mtketh_debugfs_reset':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:680:39: error: 'struct <anonymous>' has no member named 'force'
  680 |                 atomic_set(&eth->reset.force, 0);
      |                                       ^
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:683:44: error: 'struct <anonymous>' has no member named 'force'
  683 |                 if (atomic_read(&eth->reset.force))
      |                                            ^
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:689:39: error: 'struct <anonymous>' has no member named 'force'
  689 |                 atomic_set(&eth->reset.force, 1);
      |                                       ^
In file included from /media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:29:
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_agg_cnt_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:118:37: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  118 |         u32 reg_val1 = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));           \
      |                                     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1736:17: note: in expansion of macro 'SET_PDMA_RXRING_MAX_AGG_CNT'
 1736 |                 SET_PDMA_RXRING_MAX_AGG_CNT(eth, i, cnt);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: note: each undeclared identifier is reported only once for each function it appears in
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:118:37: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  118 |         u32 reg_val1 = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));           \
      |                                     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1736:17: note: in expansion of macro 'SET_PDMA_RXRING_MAX_AGG_CNT'
 1736 |                 SET_PDMA_RXRING_MAX_AGG_CNT(eth, i, cnt);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_agg_time_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:132:36: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  132 |         u32 reg_val = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));            \
      |                                    ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1747:17: note: in expansion of macro 'SET_PDMA_RXRING_AGG_TIME'
 1747 |                 SET_PDMA_RXRING_AGG_TIME(eth, i, time);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_age_time_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:262:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  262 | #define MTK_LRO_CTRL_DW1_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:140:37: note: in expansion of macro 'MTK_LRO_CTRL_DW1_CFG'
  140 |         u32 reg_val1 = mtk_r32(eth, MTK_LRO_CTRL_DW1_CFG(x));           \
      |                                     ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1758:17: note: in expansion of macro 'SET_PDMA_RXRING_AGE_TIME'
 1758 |                 SET_PDMA_RXRING_AGE_TIME(eth, i, time);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hwlro_ring_enable_ctrl':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:263:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  263 | #define MTK_LRO_CTRL_DW2_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + 0x4 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.h:160:36: note: in expansion of macro 'MTK_LRO_CTRL_DW2_CFG'
  160 |         u32 reg_val = mtk_r32(eth, MTK_LRO_CTRL_DW2_CFG(x));            \
      |                                    ^~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:1779:17: note: in expansion of macro 'SET_PDMA_RXRING_VALID'
 1779 |                 SET_PDMA_RXRING_VALID(eth, i, enable);
      |                 ^~~~~~~~~~~~~~~~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c: In function 'hw_lro_auto_tlb_read':
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_soc.h:262:42: error: 'reg_map' undeclared (first use in this function); did you mean 'regmap'?
  262 | #define MTK_LRO_CTRL_DW1_CFG(x)         (reg_map->pdma.lro_ring_ctrl_dw1 + (x * 0x40))
      |                                          ^~~~~~~
/media/data_ext/git/kernel/BPI-R2-4.14/drivers/net/ethernet/mediatek/mtk_eth_dbg.c:2009:40: note: in expansion of macro 'MTK_LRO_CTRL_DW1_CFG'
 2009 |                 reg_op1 = mtk_r32(eth, MTK_LRO_CTRL_DW1_CFG(i));
      |                                        ^~~~~~~~~~~~~~~~~~~~
make[7]: *** [/media/data_ext/git/kernel/BPI-R2-4.14/scripts/Makefile.build:194: drivers/net/ethernet/mediatek/mtk_eth_dbg.o] Error 1

fix missing reg_map

/usr/bin/aarch64-linux-gnu-ld: Unexpected GOT/PLT entries detected!
/usr/bin/aarch64-linux-gnu-ld: Unexpected run-time procedure linkages detected!
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.o: in function `mt7530_mdio_w32':
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:391:(.text+0x4b4): undefined reference to `_mtk_mdio_write_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.c:392:(.text+0x4c8): undefined reference to `_mtk_mdio_write_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.c:393:(.text+0x4dc): undefined reference to `_mtk_mdio_write_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.o: in function `mt7530_mdio_r32':
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:411:(.text+0x544): undefined reference to `_mtk_mdio_write_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.c:412:(.text+0x554): undefined reference to `_mtk_mdio_read_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.c:413:(.text+0x568): undefined reference to `_mtk_mdio_read_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.o: in function `mtketh_debugfs_write':
drivers/net/ethernet/mediatek/mtk_eth_dbg.c:654:(.text+0x878): undefined reference to `_mtk_mdio_write_c22'
/usr/bin/aarch64-linux-gnu-ld: drivers/net/ethernet/mediatek/mtk_eth_dbg.c:656:(.text+0x890): undefined reference to `_mtk_mdio_read_c22'

fix last linking errors